apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: plant-simulator
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: plant-simulator
    spec:
      containers:
        - name: plant-simulator
          image: 'joesan/plant-simulator:latest'
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: plant-simulator-service
  labels:
    name: plant-simulator-service
spec:
  ports:
    - port: 8080
      targetPort: 9000
      protocol: TCP
      name: plant-simulator-service-port
  selector:
    app: plant-simulator
  type: ClusterIP
